### ISSUE TITLE
EPrivilegeExceptions and EExternalExceptions when running project with CodeCoverage.exe

### ISSUE THREAD

**Issue by joachimmarder** [mendrix/DelphiCodeCoverage#1] opened 2021-03-04 08:58 UTC
When I run a project with `CodeCoverage.exe` from https://sourceforge.net/projects/delphicodecoverage/files/1.0%20RC12/ the monitored project often fails with a `EPrivilegeException` or a `EExternalException`. This happens for both 32 and 64 bit apps and occurs with two different projects.

Did any else experience similar problems?

@mendrix: Do you plan to publish releases here? The code seems newer than on the SourceForge site.

**Comment by mendrix** [comment] 2021-03-05 07:50
I have seens this multiple times, but most of the cases are related to memory corruption in the program executed. Have you tried running your original program with EurekaLog and checked if there are no memory issues there? (eg interface or object that is freeed twice)

**Comment by joachimmarder** [comment] 2021-03-05 11:31
We use MadExcept instead of Eurekalog, but yes. The issues started when we executed the Tests with CodeCoverage and stopped when we no longer executed them with CodeCoverage. Also, the exception types are very unusual.

**Comment by mendrix** [comment] 2021-03-05 14:07
It looks like the same issue if have fixed in [this commit](https://github.com/mendrix/DelphiCodeCoverage/commit/249089a930e94fe520d2009b8252ffcfda62dde7).

**Comment by joachimmarder** [comment] 2021-03-05 14:39
That sounds good! However, with this change the Win64 builds don't compile:
```
[dcc64 Error] Debugger.pas(906): E2003 Undeclared identifier: 'Rip'
[dcc64 Fatal Error] CodeCoverage.dpr(21): F2063 Could not compile used unit 'Debugger.pas'
```
Is there a commit missing? Or can you publish an official release of you build?

**Comment by mendrix** [comment] 2021-03-05 21:39
I have had a look tonight and it looks like JwaWinNT.pas is outdated. The _CONTEXT record is not yet Win64 compatible (therefore the Rip-register is in Win64), but we can't simply switch to Winapi.Windows, because of some other functionality in the debugger. For now you should use the Win32 version (we are using that version in production).

**Comment by mendrix** [comment] 2021-03-06 13:47
Can you retry with `master` and see if this issue still exists?

**Comment by joachimmarder** [comment] 2021-03-08 09:37
I first tried a Win64 release build, which crashes with an `EAccessViolation` at start with this call stack:

```
:00007FFC93AEF7CC ; C:\Windows\System32\dbghelp.dll
:00007FFC93AEF624 ; C:\Windows\System32\dbghelp.dll
:00007FFC93AEE322 ; C:\Windows\System32\dbghelp.dll
:00007FFC93AEE0C6 ; C:\Windows\System32\dbghelp.dll
:00007FFC93AEDFE5 ; C:\Windows\System32\dbghelp.dll
:00007FFC93AEDEC6 ; C:\Windows\System32\dbghelp.dll
:00007FFC93AEDCEA ; C:\Windows\System32\dbghelp.dll
:000000000070AF3E TArray.QuickSort<EmmaMetaData.TMethodDescriptor> + $7E
:000000000070A72B {System.Generics.Collections}TList<EmmaMetaData.TClassDescriptor>.TEnumerator.Create + $B
:0000000000708233 {System.Generics.Collections}TList<EmmaMetaData.TMethodDescriptor>.InsertRange + $D3
:0000000000707A15 {System.Generics.Collections}TList<EmmaMetaData.TMethodDescriptor>.InternalNotify + $15
EmmaMetaData.TCoverageOptions.Create(0)
:000000000070C2EF ; D:\Projects\DelphiCodeCoverage\trunk\build\Win64\CodeCoverage.exe

```

A debug build seems to work though.

**Comment by joachimmarder** [comment] 2021-03-08 09:40
OK, turning off optimization in Delphi 10.4.2 for the release builds makes the AV disappear. So it could be a problem with code-gen of the compiler.

**Comment by mendrix** [comment] 2021-03-08 11:15
Did your original issue disappear? And can you make a seperate issue for the EAccessViolation? I have compiled it with Delphi 10.4.2 this weekend and had no problems. Do you have reproduction?

**Comment by joachimmarder** [comment] 2021-03-08 13:42
> Did your original issue disappear?

Yes, looks good so far.


>  I have compiled it with Delphi 10.4.2 this weekend and had no problems. Do you have reproduction?

Would you mind publishing your builds as official release? I can then try if this happens too wit those and will create an issue for it.

**Closed** 2021-03-08 16:42 UTC
